conformant = "Unsupported"
notes = """
Does not support `typing.Unpack`.
Does not support unpacked tuples within a tuple type form.
"""
output = """
File "tuples_unpacked.py", line 13, in <module>: typing.Unpack not supported yet [not-supported-yet]
File "tuples_unpacked.py", line 13, in <module>: typing.TypeVarTuple not supported yet [not-supported-yet]
File "tuples_unpacked.py", line 16, in <module>: Invalid type annotation '<instance of tuple>'  [invalid-annotation]
File "tuples_unpacked.py", line 17, in func1: Tuple[Any] [assert-type]
File "tuples_unpacked.py", line 18, in func1: Invalid type annotation '<instance of tuple>'  [invalid-annotation]
File "tuples_unpacked.py", line 19, in func1: Invalid type annotation '<instance of tuple>'  [invalid-annotation]
File "tuples_unpacked.py", line 25, in <module>: Invalid type annotation '<instance of tuple>'  [invalid-annotation]
File "tuples_unpacked.py", line 26, in func2: Invalid type annotation '<instance of tuple>'  [invalid-annotation]
File "tuples_unpacked.py", line 31, in <module>: Type annotation for u1 does not match type of assignment [annotation-type-mismatch]
File "tuples_unpacked.py", line 31, in <module>: Invalid type annotation 'tuple[*tuple[int], *tuple[int]]'  [invalid-annotation]
File "tuples_unpacked.py", line 31, in <module>: Invalid type annotation '<instance of tuple>'  [invalid-annotation]
File "tuples_unpacked.py", line 31, in <module>: Function list.extend was called with the wrong arguments [wrong-arg-types]
File "tuples_unpacked.py", line 32, in <module>: Tuple[Any] [assert-type]
File "tuples_unpacked.py", line 33, in <module>: Invalid type annotation '<instance of tuple>'  [invalid-annotation]
File "tuples_unpacked.py", line 33, in <module>: Function list.extend was called with the wrong arguments [wrong-arg-types]
File "tuples_unpacked.py", line 38, in <module>: Invalid type annotation '<instance of tuple>'  [invalid-annotation]
File "tuples_unpacked.py", line 38, in <module>: Function list.extend was called with the wrong arguments [wrong-arg-types]
File "tuples_unpacked.py", line 39, in <module>: Invalid type annotation '<instance of tuple>'  [invalid-annotation]
File "tuples_unpacked.py", line 40, in <module>: Invalid type annotation '<instance of tuple>'  [invalid-annotation]
File "tuples_unpacked.py", line 40, in <module>: Function list.extend was called with the wrong arguments [wrong-arg-types]
File "tuples_unpacked.py", line 41, in <module>: Invalid type annotation '<instance of tuple>'  [invalid-annotation]
File "tuples_unpacked.py", line 41, in <module>: Function list.extend was called with the wrong arguments [wrong-arg-types]
File "tuples_unpacked.py", line 46, in <module>: Function TypeVarTuple.__init__ expects 1 arg(s), got 2 [wrong-arg-count]
File "tuples_unpacked.py", line 49, in <module>: Invalid type annotation '<instance of Tuple[nothing, ...]>'  [invalid-annotation]
File "tuples_unpacked.py", line 50, in func3: Invalid type annotation 'tuple[*tuple[str], *Ts]'  [invalid-annotation]
File "tuples_unpacked.py", line 51, in func3: Invalid type annotation 'tuple[*tuple[str, ...], *Ts]'  [invalid-annotation]
"""
conformance_automated = "Fail"
errors_diff = """
Line 59: Expected 1 errors
Lines 60, 61: Expected error (tag 't14')
Line 13: Unexpected errors ['File "tuples_unpacked.py", line 13, in <module>: typing.Unpack not supported yet [not-supported-yet]', 'File "tuples_unpacked.py", line 13, in <module>: typing.TypeVarTuple not supported yet [not-supported-yet]']
Line 16: Unexpected errors ['File "tuples_unpacked.py", line 16, in <module>: Invalid type annotation \\'<instance of tuple>\\'  [invalid-annotation]']
Line 17: Unexpected errors ['File "tuples_unpacked.py", line 17, in func1: Tuple[Any] [assert-type]']
Line 18: Unexpected errors ['File "tuples_unpacked.py", line 18, in func1: Invalid type annotation \\'<instance of tuple>\\'  [invalid-annotation]']
Line 19: Unexpected errors ['File "tuples_unpacked.py", line 19, in func1: Invalid type annotation \\'<instance of tuple>\\'  [invalid-annotation]']
Line 25: Unexpected errors ['File "tuples_unpacked.py", line 25, in <module>: Invalid type annotation \\'<instance of tuple>\\'  [invalid-annotation]']
Line 26: Unexpected errors ['File "tuples_unpacked.py", line 26, in func2: Invalid type annotation \\'<instance of tuple>\\'  [invalid-annotation]']
Line 31: Unexpected errors ['File "tuples_unpacked.py", line 31, in <module>: Type annotation for u1 does not match type of assignment [annotation-type-mismatch]', 'File "tuples_unpacked.py", line 31, in <module>: Invalid type annotation \\'tuple[*tuple[int], *tuple[int]]\\'  [invalid-annotation]', 'File "tuples_unpacked.py", line 31, in <module>: Invalid type annotation \\'<instance of tuple>\\'  [invalid-annotation]', 'File "tuples_unpacked.py", line 31, in <module>: Function list.extend was called with the wrong arguments [wrong-arg-types]']
Line 32: Unexpected errors ['File "tuples_unpacked.py", line 32, in <module>: Tuple[Any] [assert-type]']
Line 33: Unexpected errors ['File "tuples_unpacked.py", line 33, in <module>: Invalid type annotation \\'<instance of tuple>\\'  [invalid-annotation]', 'File "tuples_unpacked.py", line 33, in <module>: Function list.extend was called with the wrong arguments [wrong-arg-types]']
Line 38: Unexpected errors ['File "tuples_unpacked.py", line 38, in <module>: Invalid type annotation \\'<instance of tuple>\\'  [invalid-annotation]', 'File "tuples_unpacked.py", line 38, in <module>: Function list.extend was called with the wrong arguments [wrong-arg-types]']
Line 39: Unexpected errors ['File "tuples_unpacked.py", line 39, in <module>: Invalid type annotation \\'<instance of tuple>\\'  [invalid-annotation]']
Line 46: Unexpected errors ['File "tuples_unpacked.py", line 46, in <module>: Function TypeVarTuple.__init__ expects 1 arg(s), got 2 [wrong-arg-count]']
Line 49: Unexpected errors ['File "tuples_unpacked.py", line 49, in <module>: Invalid type annotation \\'<instance of Tuple[nothing, ...]>\\'  [invalid-annotation]']
Line 50: Unexpected errors ['File "tuples_unpacked.py", line 50, in func3: Invalid type annotation \\'tuple[*tuple[str], *Ts]\\'  [invalid-annotation]']
"""
